name: Run Data Ingestion Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_distpatch:

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setuo-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: pip install -r etl/requirements.txt
      
      - name: Run ingestion script
        env:
          DB_URL: ${{ secrets.DB_URL }}
          MDH_API_KEY: ${{ secrets.MDH_API_KEY }}
        run: python -m etl.src.main
